export const STATES = Object.freeze({
  UNINITIALIZED: "UNINITIALIZED",
  LOADING: "LOADING",
  READY: "READY",
  PLAYING_FORWARD: "PLAYING_FORWARD",
  PLAYING_REVERSE: "PLAYING_REVERSE",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
  DESTROYED: "DESTROYED"
});
